import { Inter } from 'next/font/google'

import { StyledJsxRegistry } from './components/StyledJsxRegistry'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledJsxRegistry>{children}</StyledJsxRegistry>
    </body>
  </html>
)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default RootLayout
